import { expect, test } from '@playwright/test'
import { clerk, clerkSetup, setupClerkTestingToken } from '@clerk/testing/playwright'

test.beforeAll(async () => { await clerkSetup() })

test('signed-out visitors cannot read or write the plan', async ({ page, request }, testInfo) => {
  for (const path of ['/api/plan', '/api/%70lan']) {
    expect((await request.get(path)).status()).toBe(401)
    expect((await request.put(path, { data: {} })).status()).toBe(401)
  }
  await setupClerkTestingToken({ page })
  await page.goto('/')
  await expect(page).toHaveURL(/\/sign-in/)
  await expect(page.getByTestId('current-worth')).toHaveCount(0)
  await expect(page.getByRole('heading', { name: 'Sign in to Worthwhile' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('sign-in.png'), fullPage: true })
  await page.getByRole('link', { name: 'Sign up', exact: true }).click()
  await expect(page).toHaveURL(/\/sign-up/)
  await expect(page.getByRole('heading', { name: 'Create your account' })).toBeVisible()
})

test('continue without signing in opens an isolated editable guest plan', async ({ page, request }, testInfo) => {
  const planRequests: string[] = []
  const errors: string[] = []
  page.on('request', request => {
    if (new URL(request.url()).pathname === '/api/plan') planRequests.push(request.method())
  })
  page.on('pageerror', error => errors.push(error.message))
  page.on('dialog', dialog => dialog.accept())
  await setupClerkTestingToken({ page })
  await page.goto('/sign-in')
  await page.getByRole('link', { name: 'Continue without signing in', exact: true }).click()
  await expect(page).toHaveURL(/\/guest$/)
  await expect(page.getByTestId('current-worth')).toHaveText('$0')
  await expect(page.getByRole('status')).toContainText('Changes are not saved')
  await expect(page.getByRole('button', { name: 'Save changes', exact: true })).toHaveCount(0)
  await page.getByLabel('Starting cash', { exact: true }).fill('2500')
  await page.getByRole('button', { name: 'Add income', exact: true }).click()
  await page.getByLabel('Name', { exact: true }).fill('Guest income')
  await page.getByLabel('Amount (USD)', { exact: true }).fill('1000')
  await page.getByRole('dialog').getByRole('button', { name: 'Add income', exact: true }).click()
  await page.getByLabel('Selected forecast month').fill('1')
  await expect(page.getByTestId('current-worth')).toHaveText('$2,500')
  await expect(page.getByTestId('projected-worth')).toHaveText('$3,500')
  await expect(page.locator('.forecast-chart svg')).toBeVisible()
  await expect(page.getByRole('link', { name: 'Sign in', exact: true })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('guest-plan.png'), fullPage: true })
  await page.reload()
  await expect(page.getByTestId('current-worth')).toHaveText('$0')
  await expect(page.locator('.empty-ledger')).toBeVisible()
  await page.getByRole('link', { name: 'Sign in', exact: true }).click()
  await expect(page).toHaveURL(/\/sign-in/)
  await page.goto('/guest')
  await expect(page.getByTestId('current-worth')).toHaveText('$0')
  expect(planRequests).toEqual([])
  expect(errors).toEqual([])
  expect((await request.get('/api/plan')).status()).toBe(401)
  expect((await request.put('/api/plan', { data: {} })).status()).toBe(401)
})

test('another signed-in account cannot access the owner plan', async ({ page }) => {
  test.skip(!process.env.E2E_CLERK_USER_ID || !process.env.E2E_CLERK_OTHER_EMAIL, 'Requires dedicated owner and non-owner test accounts.')
  await setupClerkTestingToken({ page })
  await page.goto('/sign-in')
  await clerk.signIn({ page, emailAddress: process.env.E2E_CLERK_OTHER_EMAIL! })
  await page.goto('/')
  await expect(page.getByRole('alert')).toContainText('This account cannot access the plan.')
  await expect(page.getByTestId('current-worth')).toHaveCount(0)
  expect((await page.request.get('/api/plan')).status()).toBe(403)
  expect((await page.request.put('/api/plan', { data: {} })).status()).toBe(403)
})

test('the owner can sign out without leaving financial data visible', async ({ page }) => {
  test.skip(!process.env.E2E_CLERK_USER_ID || !process.env.E2E_CLERK_USER_EMAIL, 'Requires a dedicated owner test account.')
  await setupClerkTestingToken({ page })
  await page.goto('/sign-in')
  await clerk.signIn({ page, emailAddress: process.env.E2E_CLERK_USER_EMAIL! })
  const response = await page.goto('/')
  expect(response?.headers()['cache-control']).toContain('no-store')
  await expect(page.getByTestId('current-worth')).toBeVisible()
  await page.getByRole('button', { name: 'Open user button' }).click()
  await page.getByText('Sign out', { exact: true }).click()
  await expect(page).toHaveURL(/\/sign-in/)
  await expect(page.getByTestId('current-worth')).toHaveCount(0)
  expect((await page.request.get('/api/plan')).status()).toBe(401)
  await page.goto('/')
  await expect(page).toHaveURL(/\/sign-in/)
})