import { expect, test as base, type Page } from '@playwright/test'
import { clerk, clerkSetup, setupClerkTestingToken } from '@clerk/testing/playwright'
import { spawn } from 'node:child_process'
import { once } from 'node:events'
import { mkdtempSync, rmSync } from 'node:fs'
import { createServer } from 'node:net'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { emptyPlan } from '../shared/schemas/financial-plan'

const test = base.extend({
  request: async ({ page }, use) => {
    await setupClerkTestingToken({ page })
    await page.goto('/sign-in')
    await clerk.signIn({ page, emailAddress: process.env.E2E_CLERK_USER_EMAIL! })
    await page.goto('/')
    await use(page.request)
  },
})

test.skip(!process.env.E2E_CLERK_USER_EMAIL, 'Requires a dedicated Clerk development test account.')
test.beforeAll(async () => { await clerkSetup() })

async function addEntry(page: Page, category: string, name: string, fields: Record<string, string>) {
  await page.getByRole('tab', { name: new RegExp(`^${category}`) }).click()
  const singular = category === 'Debt' ? 'liability' : category === 'Expenses' ? 'expense' : category === 'Invest' ? 'investment' : 'income'
  await page.getByRole('button', { name: `Add ${singular}`, exact: true }).click()
  if (category === 'Expenses') await page.getByRole('menuitem', { name: 'Add expense' }).click()
  await page.getByLabel('Name', { exact: true }).fill(name)
  for (const [label, value] of Object.entries(fields)) await page.getByLabel(label, { exact: true }).fill(value)
  await page.getByRole('dialog').getByRole('button', { name: `Add ${singular}`, exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.locator('.ledger-entry-card').filter({ hasText: name })).toBeVisible()
}

async function setStartingCash(page: Page, amount: string) {
  const card = page.locator('.ledger-cash-card')
  await card.getByRole('button', { name: 'Edit', exact: true }).click()
  await card.getByLabel('Starting cash', { exact: true }).fill(amount)
  await card.getByRole('button', { name: 'Save', exact: true }).click()
}

test.beforeEach(async ({ request }) => {
  const saved = await (await request.get('/api/plan')).json()
  const response = await request.put('/api/plan', { data: { plan: emptyPlan(), revision: saved.revision } })
  expect(response.ok()).toBeTruthy()
})

test('adds tax from expenses and updates its estimate as details change', async ({ page }) => {
  await page.goto('/')
  await addEntry(page, 'Income', 'Salary', { 'Amount (USD)': '5000' })
  await expect(page.getByRole('button', { name: 'Tax details' })).toHaveCount(0)
  await expect(page.getByText('Estimated tax')).toHaveCount(0)
  await page.getByRole('tab', { name: /^Expenses/ }).click()
  await page.getByRole('button', { name: 'Add expense', exact: true }).click()
  await page.getByRole('menuitem', { name: 'Add tax' }).click()
  const dialog = page.getByRole('dialog', { name: 'Tax details' })
  await expect(dialog).toBeVisible()
  await dialog.getByLabel('State of residence (2 letters)').fill('TX')
  await dialog.getByLabel('Itemized deductions (USD)').fill('20000')
  await expect(dialog.getByText('Estimated annual total').locator('..')).toContainText('$4,552.00')
  await dialog.getByLabel('Additional exemptions (USD)').fill('5000')
  await expect(dialog.getByText('Estimated annual total').locator('..')).toContainText('$3,952.00')
  await expect(dialog.getByRole('button', { name: 'Calculate taxes' })).toHaveCount(0)
  await dialog.getByRole('button', { name: 'Close' }).click()
  await expect(page.getByRole('region', { name: 'Estimated tax expense' })).toContainText('$3,952.00')
  await page.getByRole('tab', { name: /^Income/ }).click()
  await expect(page.getByText('Estimated tax')).toHaveCount(0)
})

test('edit finances, inspect the chart, autosave and reload', async ({ page }, testInfo) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('console', message => {
    if (message.type() === 'error' || /hydration/i.test(message.text())) errors.push(message.text())
  })
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'Net worth estimator' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Save changes', exact: true })).toHaveCount(0)
  await expect(page.locator('body')).not.toContainText('Saved locally')
  await expect(page.locator('body')).not.toContainText('Private workspace')
  await expect(page.locator('body')).not.toContainText('Stored in SQLite on this computer')
  await expect(page.getByTestId('current-worth')).toHaveText('$0')
  await setStartingCash(page, '5000')
  await addEntry(page, 'Income', 'Salary', { 'Amount (USD)': '5000' })
  await addEntry(page, 'Expenses', 'Housing', { 'Amount (USD)': '2000' })
  await addEntry(page, 'Invest', 'Index fund', { 'Current value (USD)': '10000', 'Annual ROI (%)': '6' })
  await addEntry(page, 'Debt', 'Student loan', { 'Outstanding balance (USD)': '1200', 'Interest APR (%)': '0', 'Monthly payment (USD)': '100' })
  await expect(page.getByTestId('current-worth')).toHaveText('$13,800')
  const initialForecast = await page.getByTestId('projected-worth').textContent()
  await page.getByRole('tab', { name: /^Invest/ }).click()
  await page.getByRole('button', { name: 'Edit Index fund', exact: true }).click()
  await page.getByLabel('Annual ROI (%)', { exact: true }).fill('9')
  await page.getByRole('button', { name: 'Apply changes' }).click()
  await expect(page.getByTestId('projected-worth')).not.toHaveText(initialForecast!)
  const timeHorizon = page.getByLabel('Time horizon in years', { exact: true })
  await expect(timeHorizon).toHaveAttribute('readonly', '')
  await page.getByLabel('Increase time horizon', { exact: true }).click({ clickCount: 10 })
  await expect(timeHorizon).toHaveValue('20 years')
  await expect(page.locator('.forecast-chart svg')).toBeVisible()
  const paths = await page.locator('.forecast-chart path').evaluateAll(elements => elements.filter(element => (element.getAttribute('d')?.length ?? 0) > 20).length)
  expect(paths).toBeGreaterThan(2)
  await page.getByLabel('Selected forecast month').fill('120')
  await expect(page.locator('.month-selector label')).toContainText('2036')
  await expect(page.getByTestId('save-status')).toHaveText('')
  await page.reload()
  await expect(page.getByTestId('current-worth')).toHaveText('$13,800')
  await expect(timeHorizon).toHaveValue('20 years')
  await page.getByRole('tab', { name: 'Annual table', exact: true }).click()
  await expect(page.locator('.annual-table tbody tr')).toHaveCount(21)
  await page.getByRole('tab', { name: 'Chart', exact: true }).click()
  await page.getByRole('tab', { name: /^Invest/ }).click()
  await page.getByLabel('Selected forecast month').fill('120')
  await page.screenshot({ path: testInfo.outputPath(`${testInfo.project.name}-forecast.png`), fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  expect(errors).toEqual([])

  for (const [category, name] of [['Income', 'Salary'], ['Expenses', 'Housing'], ['Invest', 'Index fund'], ['Debt', 'Student loan']]) {
    await page.getByRole('tab', { name: new RegExp(`^${category}`) }).click()
    await page.getByRole('button', { name: `Edit ${name}`, exact: true }).click()
    await page.getByLabel('Name', { exact: true }).fill(`${name} revised`)
    await page.getByRole('button', { name: 'Apply changes' }).click()
    await page.getByRole('button', { name: `Delete ${name} revised`, exact: true }).click()
    await page.getByRole('button', { name: 'Delete entry', exact: true }).click()
    await expect(page.locator('.empty-ledger')).toBeVisible()
  }
  await expect(page.getByTestId('save-status')).toHaveText('')
  await page.reload()
  await expect(page.getByTestId('current-worth')).toHaveText('$5,000')
})

test('shows deficits, handles failed saves, and rejects conflicting updates', async ({ page, request }) => {
  await page.goto('/')
  await page.route('**/api/plan', route => route.request().method() === 'PUT' ? route.fulfill({ status: 503, contentType: 'application/json', body: '{}' }) : route.continue())
  await addEntry(page, 'Debt', 'Underpaid loan', { 'Outstanding balance (USD)': '1000', 'Interest APR (%)': '12', 'Monthly payment (USD)': '1' })
  await expect(page.getByText('Cash shortfall from', { exact: false })).toBeVisible()
  await expect(page.getByText('Payments do not cover interest:', { exact: false })).toBeVisible()
  await expect(page.getByTestId('projected-worth')).toContainText('-$')
  await expect(page.getByRole('alert')).toContainText('could not be saved')
  await expect(page.getByTestId('save-status')).toHaveText('Not saved')
  await expect(page.locator('.ledger-entry-card').filter({ hasText: 'Underpaid loan' })).toBeVisible()
  await page.unroute('**/api/plan')
  await page.getByRole('button', { name: 'Retry', exact: true }).click()
  await expect(page.getByTestId('save-status')).toHaveText('')
  await expect(page.getByRole('alert')).toHaveCount(0)
  const latest = await (await request.get('/api/plan')).json()
  expect((await request.put('/api/plan', { data: { plan: latest.plan, revision: latest.revision } })).ok()).toBeTruthy()
  await setStartingCash(page, '100')
  await expect(page.getByRole('alert')).toContainText('Another tab')
  await page.getByRole('button', { name: 'Reload saved plan' }).click()
  await page.getByRole('button', { name: 'Reload plan', exact: true }).click()
  await expect(page.locator('.ledger-cash-card')).toContainText('$0')
})

test('validates inputs and protects the local API', async ({ page, request }) => {
  const current = await (await request.get('/api/plan')).json()
  expect((await request.put('/api/plan', { data: { ...current, plan: { ...current.plan, startingCash: -100 } } })).status()).toBe(400)
  expect((await request.put('/api/plan', { data: current, headers: { Origin: 'https://example.com' } })).status()).toBe(403)
  expect((await request.get('/api/plan', { headers: { Host: 'example.com' } })).status()).toBe(403)
  await page.goto('/')
  await page.getByRole('tab', { name: /^Invest/ }).click()
  await page.getByRole('button', { name: 'Add investment', exact: true }).click()
  await page.getByLabel('Name', { exact: true }).fill('A very long investment name that must wrap without overlapping controls or making the page wider')
  await page.getByLabel('Current value (USD)', { exact: true }).fill('100')
  await page.getByLabel('Annual ROI (%)', { exact: true }).fill('-101')
  await page.getByRole('dialog').getByRole('button', { name: 'Add investment', exact: true }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.getByLabel('Annual ROI (%)', { exact: true }).fill('-100')
  await page.getByRole('dialog').getByRole('button', { name: 'Add investment', exact: true }).click()
  await expect(page.getByTestId('projected-worth')).toHaveText('$0')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  const timeHorizon = page.getByLabel('Time horizon in years', { exact: true })
  await expect(timeHorizon).toHaveAttribute('readonly', '')
  await page.getByLabel('Decrease time horizon', { exact: true }).click()
  await expect(timeHorizon).toHaveValue('9 years')
  await page.getByLabel('Increase time horizon', { exact: true }).click()
  await expect(timeHorizon).toHaveValue('10 years')
  await expect(page.getByRole('alert')).toHaveCount(0)
  await expect(page.getByTestId('projected-worth')).toHaveText('$0')
})

test('adjusts investment allocations and follows the selected projection month', async ({ page }) => {
  await page.goto('/')
  await addEntry(page, 'Income', 'Monthly pay', { 'Amount (USD)': '1000' })
  await addEntry(page, 'Invest', 'Growth fund', { 'Current value (USD)': '0', 'Annual ROI (%)': '12', 'Surplus allocation (%)': '60' })
  await addEntry(page, 'Invest', 'Reserve fund', { 'Current value (USD)': '0', 'Annual ROI (%)': '0', 'Surplus allocation (%)': '25' })
  await expect(page.getByText('15.00% of surplus stays in cash', { exact: true })).toBeVisible()
  await page.getByLabel('Selected forecast month').fill('1')
  await expect(page.getByTestId('projected-worth')).toHaveText('$1,000')
  await expect(page.locator('.projected .small-badge')).toHaveText('1 month')
  await expect(page.locator('.projected .metric-note')).toContainText('$1,000 projected change')
  await expect(page.locator('.month-breakdown')).toContainText('$150')
  await expect(page.locator('.month-breakdown')).toContainText('$850')
  await page.getByLabel('Selected forecast month').fill('2')
  await expect(page.getByTestId('projected-worth')).toHaveText('$2,006')
  await expect(page.locator('.projected .small-badge')).toHaveText('2 months')
  await page.getByLabel('Selected forecast month').fill('13')
  await expect(page.locator('.projected .small-badge')).toHaveText('1 year 1 month')
  await expect(page.getByTestId('projected-worth')).toHaveText((await page.locator('.breakdown-worth strong').textContent())!)
  await page.getByRole('button', { name: 'Edit Growth fund', exact: true }).click()
  await page.getByLabel('Surplus allocation (%)', { exact: true }).fill('80')
  await page.getByRole('button', { name: 'Apply changes' }).click()
  await expect(page.getByRole('alert')).toContainText('Allocations cannot exceed 100%')
  await page.getByLabel('Surplus allocation (%)', { exact: true }).fill('50')
  await page.getByRole('button', { name: 'Apply changes' }).click()
  await expect(page.getByText('25.00% of surplus stays in cash', { exact: true })).toBeVisible()
  await expect(page.getByTestId('save-status')).toHaveText('')
  await page.reload()
  await page.getByRole('tab', { name: /^Invest/ }).click()
  await expect(page.locator('.ledger-entry-card').filter({ hasText: 'Growth fund' })).toContainText('50%')
  await expect(page.locator('.ledger-entry-card').filter({ hasText: 'Reserve fund' })).toContainText('25%')
  await page.getByLabel('Selected forecast month').fill('0')
  await expect(page.locator('.projected .small-badge')).toHaveText('Today')
  await expect(page.getByTestId('projected-worth')).toHaveText('$0')
  await expect(page.getByTestId('save-status')).toHaveText('')
})

test('creates monthly dollar targets and switches allocation modes without losing settings', async ({ page, request }, testInfo) => {
  await page.goto('/')
  await addEntry(page, 'Income', 'Pay', { 'Amount (USD)': '1000' })
  await addEntry(page, 'Invest', 'Fund', { 'Current value (USD)': '0', 'Annual ROI (%)': '0', 'Surplus allocation (%)': '50' })
  for (const [name, amount] of [['HSA', '250.50'], ['401k', '400']]) {
    await page.getByRole('button', { name: 'Add investment', exact: true }).click()
    await page.getByLabel('Name', { exact: true }).fill(name!)
    await page.getByLabel('Current value (USD)', { exact: true }).fill('0')
    await page.getByLabel('Annual ROI (%)', { exact: true }).fill('0')
    await page.getByRole('tab', { name: '$ per month', exact: true }).click()
    await page.getByLabel('Monthly contribution (USD)', { exact: true }).fill(amount!)
    await page.getByRole('dialog').getByRole('button', { name: 'Add investment', exact: true }).click()
    await expect(page.getByRole('dialog')).toHaveCount(0)
  }
  await expect(page.locator('.ledger-entry-card').filter({ hasText: 'HSA' })).toContainText('$250.50 / month')
  await expect(page.locator('.ledger-entry-card').filter({ hasText: '401k' })).toContainText('$400.00 / month')
  await expect(page.locator('.ledger-entry-card').filter({ hasText: 'Fund' })).toContainText('50% of remainder')
  await page.getByLabel('Selected forecast month').fill('1')
  await expect(page.getByTestId('projected-worth')).toHaveText('$1,000')
  await expect(page.locator('.month-breakdown')).toContainText('$175')
  await expect(page.locator('.month-breakdown')).toContainText('$825')
  await expect(page.getByTestId('save-status')).toHaveText('')
  const saved = await (await request.get('/api/plan')).json()
  expect(saved.plan.investments).toEqual(expect.arrayContaining([
    expect.objectContaining({ name: 'HSA', monthlyContribution: 25050 }),
    expect.objectContaining({ name: '401k', monthlyContribution: 40000 }),
    expect.objectContaining({ name: 'Fund', allocation: 50 }),
  ]))
  await page.reload()
  await page.getByRole('tab', { name: /^Invest/ }).click()
  await page.getByRole('button', { name: 'Edit HSA', exact: true }).click()
  await expect(page.getByRole('tab', { name: '$ per month', exact: true })).toHaveAttribute('aria-selected', 'true')
  await expect(page.getByLabel('Monthly contribution (USD)', { exact: true })).toHaveValue('250.5')
  const dialogBounds = await page.getByRole('dialog').boundingBox()
  const viewport = page.viewportSize()!
  expect(dialogBounds!.x).toBeGreaterThanOrEqual(0)
  expect(dialogBounds!.y).toBeGreaterThanOrEqual(0)
  expect(dialogBounds!.x + dialogBounds!.width).toBeLessThanOrEqual(viewport.width)
  expect(dialogBounds!.y + dialogBounds!.height).toBeLessThanOrEqual(viewport.height)
  await page.screenshot({ path: testInfo.outputPath('monthly-allocation-editor.png') })
  await page.getByRole('tab', { name: '% of surplus', exact: true }).click()
  await page.getByLabel('Surplus allocation (%)', { exact: true }).fill('60')
  await page.getByRole('button', { name: 'Apply changes', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Allocations cannot exceed 100%')
  await page.getByLabel('Surplus allocation (%)', { exact: true }).fill('25')
  await page.getByRole('button', { name: 'Apply changes', exact: true }).click()
  await expect(page.locator('.ledger-entry-card').filter({ hasText: 'HSA' })).toContainText('25% of remainder')
  await expect(page.locator('.ledger-entry-card').filter({ hasText: '401k' })).toContainText('$400.00 / month')
  await page.getByRole('button', { name: 'Edit HSA', exact: true }).click()
  await page.getByRole('tab', { name: '$ per month', exact: true }).click()
  await page.getByLabel('Monthly contribution (USD)', { exact: true }).fill('0')
  await page.getByRole('button', { name: 'Apply changes', exact: true }).click()
  await expect(page.locator('.ledger-entry-card').filter({ hasText: 'HSA' })).toContainText('$0.00 / month')
  await expect(page.getByTestId('save-status')).toHaveText('')
  const updated = await (await request.get('/api/plan')).json()
  const hsa = updated.plan.investments.find((item: { name: string }) => item.name === 'HSA')
  expect(hsa.monthlyContribution).toBe(0)
  expect(hsa).not.toHaveProperty('allocation')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('mixed-allocations.png'), fullPage: true })
})

test('shows sourced wealth percentiles and exact yearly income totals', async ({ page, request }, testInfo) => {
  const saved = await (await request.get('/api/plan')).json()
  const savedProfile = await (await request.get('/api/profile')).json()
  expect((await request.put('/api/profile', { data: { profile: { ...savedProfile.profile, birthDate: '1994-01-01' }, revision: savedProfile.revision } })).ok()).toBe(true)
  expect((await request.put('/api/plan', { data: { plan: { ...emptyPlan(), startingCash: 19270000 }, revision: saved.revision } })).ok()).toBe(true)
  await page.goto('/')
  await expect(page.getByTestId('current-percentile')).toContainText('50th percentile')
  await expect(page.getByTestId('projected-percentile')).toContainText('50th percentile')
  await expect(page.getByTestId('current-age-percentile')).toContainText('Ages 30–34')
  await expect(page.getByTestId('projected-age-percentile')).toContainText('Ages 30–34')
  await addEntry(page, 'Income', 'Monthly pay', { 'Amount (USD)': '1000.01' })
  await page.getByRole('button', { name: 'Add income', exact: true }).click()
  await page.getByLabel('Name', { exact: true }).fill('Annual income')
  await page.getByLabel('Amount (USD)', { exact: true }).fill('125.01')
  await page.getByLabel('Frequency', { exact: true }).click()
  await page.getByRole('option', { name: 'Annual', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Add income', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.getByTestId('yearly-income')).toHaveText('$12,125.13')
  await expect(page.locator('.ledger-entry-card').filter({ hasText: 'Monthly pay' })).toContainText('$12,000.12 annualized')
  await expect(page.locator('.ledger-entry-card').filter({ hasText: 'Annual income' })).toContainText('$125.01 annualized')
  await page.getByLabel('Selected forecast month').fill('0')
  await expect(page.getByTestId('projected-percentile')).toContainText('50th percentile')
  await page.getByLabel('Selected forecast month').fill('12')
  await expect(page.getByTestId('projected-percentile')).toContainText('51st percentile')
  await expect(page.getByTestId('current-percentile')).toContainText('50th percentile')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('percentiles-yearly-income.png'), fullPage: true })
  await page.getByRole('button', { name: 'Edit Monthly pay', exact: true }).click()
  await page.getByLabel('Amount (USD)', { exact: true }).fill('2000')
  await page.getByRole('button', { name: 'Apply changes', exact: true }).click()
  await expect(page.getByTestId('yearly-income')).toHaveText('$24,125.01')
  await page.getByRole('tab', { name: /^Expenses/ }).click()
  await expect(page.getByTestId('yearly-income')).toHaveCount(0)
  await setStartingCash(page, '20000000')
  await expect(page.getByTestId('current-percentile')).toContainText('Above 99th percentile')
  await page.getByLabel('Time horizon in years', { exact: true }).fill('')
  await expect(page.getByTestId('current-percentile')).toContainText('--')
  await expect(page.getByTestId('projected-percentile')).toContainText('--')
})

test('chart tooltips follow hover without changing the selected forecast month', async ({ page }, testInfo) => {
  test.skip(testInfo.project.name === 'mobile', 'Hover-specific check; mobile uses the month slider.')
  await page.goto('/')
  const slider = page.getByLabel('Selected forecast month')
  await slider.fill('36')
  const selectedDate = await page.locator('.month-selector label').textContent()
  const selectedWorth = await page.getByTestId('projected-worth').textContent()
  const chart = page.locator('.forecast-chart svg')
  await expect(chart).toBeVisible()
  const box = (await chart.boundingBox())!
  await page.mouse.move(box.x + box.width * 0.25, box.y + box.height * 0.7)
  const tooltip = page.locator('.forecast-chart [class*="tooltip"] .font-medium').first()
  await expect(tooltip).toBeVisible()
  const firstText = await tooltip.textContent()
  await expect(page.locator('.month-selector label')).toHaveText(selectedDate!)
  await page.mouse.move(box.x + box.width * 0.75, box.y + box.height * 0.7)
  await expect(tooltip).not.toHaveText(firstText!)
  await expect(page.locator('.month-selector label')).toHaveText(selectedDate!)
  await expect(slider).toHaveValue('36')
  await expect(page.locator('.projected .small-badge')).toHaveText('3 years')
  await expect(page.getByTestId('projected-worth')).toHaveText(selectedWorth!)
  await slider.fill('12')
  await expect(page.locator('.projected .small-badge')).toHaveText('1 year')
  await expect(chart).toContainText('$')
  await expect(chart).toContainText('2026')
})

test('saved plan survives a production server process restart', async ({ request }, testInfo) => {
  test.skip(testInfo.project.name === 'mobile', 'Server persistence is independent of viewport.')
  const directory = mkdtempSync(join(tmpdir(), 'worthwhile-restart-'))
  async function startServer() {
    const probe = createServer()
    probe.listen(0, '127.0.0.1')
    await once(probe, 'listening')
    const address = probe.address()
    if (!address || typeof address === 'string') throw new Error('Expected a TCP port')
    await new Promise<void>((resolve, reject) => probe.close(error => error ? reject(error) : resolve()))
    const child = spawn(process.execPath, ['.output/server/index.mjs'], {
      env: { ...process.env, HOST: '127.0.0.1', PORT: String(address.port), NUXT_DATABASE_PATH: join(directory, 'plan.sqlite') },
      stdio: ['ignore', 'pipe', 'pipe'],
    })
    const url = await new Promise<string>((resolve, reject) => {
      child.on('error', reject)
      child.on('exit', code => reject(new Error(`Server exited before startup: ${code}`)))
      child.stdout.on('data', (output: Buffer) => {
        const address = output.toString().match(/http:\/\/127\.0\.0\.1:\d+/)?.[0]
        if (address) resolve(address)
      })
    })
    return { url, stop: async () => { const closed = once(child, 'close'); child.kill('SIGTERM'); await closed } }
  }
  let server: Awaited<ReturnType<typeof startServer>> | undefined
  try {
    server = await startServer()
    const plan = { ...emptyPlan(), startingCash: 12345 }
    const saved = await request.put(`${server.url}/api/plan`, { data: { plan, revision: 0 } })
    expect(saved.ok()).toBe(true)
    await server.stop()
    server = undefined
    server = await startServer()
    expect(await (await request.get(`${server.url}/api/plan`)).json()).toEqual({ plan, revision: 1 })
  } finally {
    await server?.stop()
    rmSync(directory, { recursive: true, force: true })
  }
})