import { expect, test, type Page } from '@playwright/test'

async function openAsset(page: Page, type: 'Car' | 'Real estate') {
  await page.getByRole('tab', { name: /^Assets/ }).click()
  await page.getByRole('button', { name: 'Add investment', exact: true }).click()
  await page.getByLabel('Asset type', { exact: true }).click()
  await page.getByRole('option', { name: type, exact: true }).click()
}

test.beforeEach(async ({ page }) => { await page.goto('/guest') })

test('manual car and home entry never calls valuation, including an outage', async ({ page }) => {
  let calls = 0
  await page.route('**/api/valuation', route => { calls++; return route.abort() })
  await openAsset(page, 'Car')
  await page.getByRole('tab', { name: 'Look up by VIN', exact: true }).click()
  await page.getByLabel('VIN', { exact: true }).fill('SHORT')
  await page.getByLabel('Mileage', { exact: true }).fill('-1')
  await page.getByLabel('ZIP code', { exact: true }).fill('INVALID')
  await page.getByRole('tab', { name: 'Enter manually', exact: true }).click()
  await page.getByLabel('Name', { exact: true }).fill('Manual car')
  await page.getByLabel('Market value (USD)').fill('12000')
  await page.getByRole('button', { name: 'Add car', exact: true }).click()
  await expect(page.locator('.ledger-entry-card').filter({ hasText: 'Manual car' })).toBeVisible()
  await expect(page.getByTestId('current-worth')).toHaveText('$12,000')
  await openAsset(page, 'Real estate')
  await page.getByLabel('Name', { exact: true }).fill('Manual home')
  await page.getByLabel('Market value (USD)').fill('300000')
  await page.getByLabel('Annual appreciation (%)').fill('2')
  await page.getByRole('button', { name: 'Add property', exact: true }).click()
  await expect(page.locator('.ledger-entry-card').filter({ hasText: 'Manual home' })).toBeVisible()
  await expect(page.getByTestId('current-worth')).toHaveText('$312,000')
  expect(calls).toBe(0)
})

test('VIN lookup prefills details, saves the override and only refreshes explicitly', async ({ page }, testInfo) => {
  const requests: unknown[] = []
  await page.route('**/api/valuation', async route => {
    requests.push(route.request().postDataJSON())
    await route.fulfill({ json: { value: 1800000, source: 'MarketCheck', fetchedAt: '2026-10-01T00:00:00.000Z', vehicle: { vin: '1HGCM82633A004352', year: 2020, make: 'Honda', model: 'Civic', trim: 'EX', mileage: 50000, zip: '78701' } } })
  })
  await openAsset(page, 'Car')
  await page.getByRole('tab', { name: 'Look up by VIN', exact: true }).click()
  await page.getByLabel('VIN', { exact: true }).fill('SHORT')
  await page.getByRole('button', { name: 'Look up estimate', exact: true }).click()
  expect(requests).toHaveLength(0)
  await page.getByLabel('VIN', { exact: true }).fill('1HGCM82633A004352')
  await page.getByLabel('Mileage', { exact: true }).fill('50000')
  await page.getByLabel('ZIP code', { exact: true }).fill('78701')
  expect(requests).toHaveLength(0)
  await page.getByRole('button', { name: 'Look up estimate', exact: true }).click()
  await expect(page.getByLabel('Market value (USD)')).toHaveValue('18000')
  await expect(page.getByLabel('Name', { exact: true })).toHaveValue('2020 Honda Civic')
  await expect(page.getByLabel('Trim', { exact: true })).toHaveValue('EX')
  await expect(page.getByText('Estimate via MarketCheck · Oct 2026')).toBeVisible()
  await page.getByLabel('Market value (USD)').fill('16500')
  await page.getByRole('button', { name: 'Add car', exact: true }).click()
  await expect(page.getByTestId('current-worth')).toHaveText('$16,500')
  await page.getByRole('button', { name: 'Edit 2020 Honda Civic', exact: true }).click()
  await expect(page.getByLabel('Market value (USD)')).toHaveValue('16500')
  await expect(page.getByText('Estimate via MarketCheck · Oct 2026')).toBeVisible()
  expect(requests).toHaveLength(1)
  await page.screenshot({ path: testInfo.outputPath('car-valuation.png') })
  await page.getByRole('button', { name: 'Refresh estimate', exact: true }).click()
  await expect(page.getByLabel('Market value (USD)')).toHaveValue('18000')
  expect(requests).toHaveLength(2)
  expect(requests[1]).toEqual(requests[0])
})

test('a VIN alone is enough to request an estimate with visible default assumptions', async ({ page }) => {
  let calls = 0
  await page.route('**/api/valuation', route => {
    calls++
    expect(route.request().postDataJSON()).toEqual({ type: 'car', vin: '1HGCM82633A004352' })
    return route.fulfill({ json: { value: 1000000, source: 'MarketCheck', fetchedAt: '2026-10-01T00:00:00.000Z', vehicle: { vin: '1HGCM82633A004352', year: 2003, make: 'Honda', model: 'Accord', mileage: 50000, zip: '50501' } } })
  })
  await openAsset(page, 'Car')
  await page.getByRole('tab', { name: 'Look up by VIN', exact: true }).click()
  await expect(page.getByText(/If omitted, MarketCheck uses 50,000 miles and ZIP 50501/)).toBeVisible()
  await page.getByLabel('VIN', { exact: true }).fill('1HGCM82633A004352')
  await page.getByRole('button', { name: 'Look up estimate', exact: true }).click()
  await expect(page.getByLabel('Market value (USD)')).toHaveValue('10000')
  await page.getByRole('button', { name: 'Add car', exact: true }).click()
  await expect(page.getByTestId('current-worth')).toHaveText('$10,000')
  expect(calls).toBe(1)
})

test('address lookup preserves the linked loan and editable estimate', async ({ page }) => {
  let calls = 0
  await page.route('**/api/valuation', route => {
    calls++
    return route.fulfill({ json: { value: 40000000, source: 'RentCast', fetchedAt: '2026-10-01T00:00:00.000Z', propertyDetails: { address: '123 Main St, Austin, TX 78701', bedrooms: 3, bathrooms: 2, squareFootage: 1800, yearBuilt: 1998 } } })
  })
  await openAsset(page, 'Real estate')
  await page.getByRole('tab', { name: 'Look up by address', exact: true }).click()
  await page.getByLabel('Street address', { exact: true }).fill('123 Main St, Austin, TX 78701')
  expect(calls).toBe(0)
  await page.getByRole('button', { name: 'Look up estimate', exact: true }).click()
  await expect(page.getByLabel('Market value (USD)')).toHaveValue('400000')
  await expect(page.getByLabel('Bedrooms', { exact: true })).toHaveValue('3')
  await expect(page.getByLabel('Year built', { exact: true })).toHaveValue('1998')
  await page.getByLabel('Name', { exact: true }).fill('Estimated home')
  await page.getByLabel('Market value (USD)').fill('390000')
  await page.getByLabel('Outstanding balance (USD)').fill('200000')
  await page.getByRole('button', { name: 'Add property', exact: true }).click()
  await expect(page.getByTestId('current-worth')).toHaveText('$190,000')
  await page.getByRole('button', { name: 'Edit Estimated home', exact: true }).click()
  await expect(page.getByLabel('Market value (USD)')).toHaveValue('390000')
  await expect(page.getByLabel('Outstanding balance (USD)')).toHaveValue('200000')
  await expect(page.getByText('Estimate via RentCast · Oct 2026')).toBeVisible()
  expect(calls).toBe(1)
})

test('failed lookup does not block switching to manual and saving', async ({ page }) => {
  await page.route('**/api/valuation', route => route.fulfill({ status: 503, json: { message: 'Unavailable' } }))
  await openAsset(page, 'Car')
  await page.getByRole('tab', { name: 'Look up by VIN', exact: true }).click()
  await page.getByLabel('VIN', { exact: true }).fill('1HGCM82633A004352')
  await page.getByLabel('Mileage', { exact: true }).fill('50000')
  await page.getByLabel('ZIP code', { exact: true }).fill('78701')
  await page.getByRole('button', { name: 'Look up estimate', exact: true }).click()
  await expect(page.getByText("Couldn't reach the valuation service — enter the value manually")).toBeVisible()
  await page.getByRole('tab', { name: 'Enter manually', exact: true }).click()
  await page.getByLabel('Name', { exact: true }).fill('Outage car')
  await page.getByLabel('Market value (USD)').fill('10000')
  await page.getByRole('button', { name: 'Add car', exact: true }).click()
  await expect(page.getByTestId('current-worth')).toHaveText('$10,000')
})
